sudo: false
language: java
jdk:
- oraclejdk8
before_script:
- mkdir -p ext
- wget http://kent.dl.sourceforge.net/project/launch4j/launch4j-3/3.12/launch4j-3.12-linux.tgz
- echo "e8f5c546e288bc207a00f06fa01e6124e4f763f4eadccb7ca359071b95f75349  launch4j-3.12-linux.tgz" | sha256sum -c
- tar -C ext -xzf launch4j-3.12-linux.tgz
- ant fetch
script:
- mvn -U -B clean package findbugs:check
- ant windist
env:
  global:
    secure: Df5FIHnieDJj8AAwgeAh779Rs+aoJ8e9WQN0ero4OfcJ2Y1G7InBZQIGesfVR1M7EX4Hf0fvmUam9zthdwi4culk+gJeOAMM/wpCqvEUyWDTd78Cr08L7PjNW8RCq5NCYhgvO1j+IzJOA3IR6h8DSS4QGZtJqPYk65ZQ1uRyAGc=
notifications:
  irc:
    on_success: change
    on_failure: always
    channels:
    - irc.freenode.org#javacard
addons:
  apt:
    packages:
    - libc6:i386
  coverity_scan:
    project:
      name: martinpaljak/GlobalPlatformPro
    notification_email: martin@martinpaljak.net
    build_command: mvn clean compile
    branch_pattern: coverity
deploy:
  - provider: releases
    prerelease: true
    file:
      - gp.jar
      - gp.exe
    api-key:
      secure: "Pn3sXjb06x932nCgRzKirytYZKKLATjc7dVFndsnf1XqPvcmdq2vproWpTetz6nT94YFepP/R26uizdJbZcf9XL1LyHf77klGFHJY/XXGJY4MeVD6l3rIckFmDFiETo8WcRTzk9jhGYM1trIRk/w8RJFawimxxn8KA8ZEIluySA="
    skip_cleanup: true
    on:
      tags: true
      repo: martinpaljak/GlobalPlatformPro
cache:
  directories:
  - $HOME/.m2
